template_path: templates/bridge.yaml
stack_name: bridge
dependencies:
  - bootstrap
parameters:
  AwsAccount: {{ environment_variable.TRAVIS_BRANCH }}
  AwsDefaultVpcId: "{{ environment_variable.AwsDefaultVpcId_prod }}"
  InitNewUserPassword: {{ environment_variable.InitNewUserPassword_prod }}
  JacobianUserPassword: {{ environment_variable.JacobianUserPassword_prod }}
  NewRelicAccountId: "{{ environment_variable.NewRelicAccountId_prod }}"
  NewRelicExternalId: "{{ environment_variable.NewRelicExternalId_prod }}"
  OperatorEmail: {{ environment_variable.OperatorEmail_prod }}
  FhcrcVpnCidrip: {{ environment_variable.FhcrcVpnCidrip_prod }}
  VpcPeeringRequesterAwsAccountId: "{{ environment_variable.VpcPeeringRequesterAwsAccountId_prod }}"

