template_path: remote-templates/GuardDutyMember.yaml
stack_name: guardduty-member
dependencies:
  - bootstrap
hooks:
  before_update:
    - !cmd "aws --profile {{ var.profile }} s3 cp s3://{{ environment_variable.AdminCentralInfraCfBucket }}/aws-infra/master/GuardDutyMember.yaml ./remote-templates/GuardDutyMember.yaml"
parameters:
  MasterAccountId: "{{ environment_variable.LogcentralAwsAccountId }}"
  InvitationId: 44b20c8f146d20f606c3d76bd36e13fd
