template_path: remote-templates/GuardDutyMember.yaml
stack_name: guardduty-member
dependencies:
  - bootstrap
parameters:
  MasterAccountId: !ssm /infra/LogcentralAwsAccountId
  InvitationId: 44b20c8f146d20f606c3d76bd36e13fd
hooks:
  before_update:
    - !cmd "curl https://raw.githubusercontent.com/Sage-Bionetworks/aws-infra/master/templates/GuardDutyMember.yaml --create-dirs -o remote-templates/GuardDutyMember.yaml"
