template_path: "prod/jumpcloud-idp.yaml"
stack_name: "jumpcloud-idp"
stack_tags:
  Department: "Platform"
  Project: "Infrastructure"
  OwnerEmail: "it@sagebase.org"
parameters:
  BridgeprodAdminMetadata: !file_contents idp/jumpcloud/bridgeprod-admin.xml
  BridgeprodiOSDeveloperMetadata: !file_contents idp/jumpcloud/bridgeprod-ios-developer.xml
dependencies:
  - "prod/cfn-cr-saml-provider.yaml"
  - "develop/iam-policies.yaml"
