template_path: remote-templates/peer-single-route.yaml
stack_name: peer-vpn-BridgeServer2-vpc
dependencies:
  - BridgeServer2-vpc
parameters:
  PeeringConnectionId: pcx-fe35e296
  VpcRouteTable: rtb-bf9851da
  VpnCidr: 10.2.0.0/16
hooks:
  before_create:
    - !cmd "curl https://raw.githubusercontent.com/Sage-Bionetworks/aws-infra/master/templates/peer-single-route.yaml --create-dirs -o remote-templates/peer-single-route.yaml"
  before_update:
    - !cmd "curl https://raw.githubusercontent.com/Sage-Bionetworks/aws-infra/master/templates/peer-single-route.yaml --create-dirs -o remote-templates/peer-single-route.yaml"
