sudo: false
language: python
python: 3.4
cache: pip
env:
  global:
  - STACK_NAME=bridge
install:
# install git-crypt
- pushd /tmp
- wget https://github.com/AGWA/git-crypt/archive/master.zip -O git-crypt.zip
- unzip git-crypt.zip
- cd git-crypt-master
- make
- popd
# get env vars
- openssl aes-256-cbc -K $encrypted_01c81fac4a66_key -iv $encrypted_01c81fac4a66_iv -in git-crypt.key.enc -out git-crypt.key -d
- /tmp/git-crypt-master/git-crypt unlock ./git-crypt.key
- rm -rf git-crypt.key
- source env_vars && source env_vars.secret
- /tmp/git-crypt-master/git-crypt lock
# install aws cli
- ./setup_aws_cli.sh
script:
- ./deploy_infra.sh
