template_path: remote-templates/vpc.yaml
stack_name: bridge-aux
dependencies:
  - bridge
parameters:
  VpcSubnetPrefix: "172.51"
  VpcName: bridge-aux
hooks:
  before_update:
    - !cmd "aws --profile {{ var.profile }} s3 cp s3://{{ environment_variable.AdminCentralInfraCfBucket }}/aws-infra/master/vpc.yaml ./remote-templates/vpc.yaml"
