template_path: templates/bridge.yaml
stack_name: bridge
dependencies:
  - bootstrap
parameters:
  AwsAccount: {{ environment_variable.TRAVIS_BRANCH }}
  AwsDefaultVpcId: "{{ environment_variable.AwsDefaultVpcId_develop }}"
  InitNewUserPassword: {{ environment_variable.InitNewUserPassword_develop }}
  NewRelicAccountId: "{{ environment_variable.NewRelicAccountId_develop }}"
  NewRelicExternalId: "{{ environment_variable.NewRelicExternalId_develop }}"
  OperatorEmail: {{ environment_variable.OperatorEmail_develop }}
  VpcPeeringRequesterAwsAccountId: "{{ environment_variable.VpcPeeringRequesterAwsAccountId_develop }}"

