template_path: remote-templates/RotateCredentials.yaml
stack_name: RotateCredentials
dependencies:
  - AccountAlertTopics
parameters:
  LambdaBucket: essentials-awss3lambdaartifactsbucket-x29ftznj6pqw
  GracePeriod: "14"
  DisableKeys: "false"
  SendEmail: "true"
  SenderEmail: it@sagebase.org
  SendReport: "true"
hooks:
  before_update:
    - !cmd "aws --profile admincentral.cfservice s3 cp s3://{{ environment_variable.AdminCentralInfraCfBucket }}/aws-infra/master/RotateCredentials.yaml ./remote-templates/RotateCredentials.yaml"
