Description: Common resources for AWS account
AWSTemplateFormatVersion: 2010-09-09
Parameters:
  InitNewUserPassword:
    Type: String
    NoEcho: true
  JacobianUserPassword:
    Type: String
    NoEcho: true
  NewRelicAccountId:
    Type: String
    NoEcho: true
  NewRelicExternalId:
    Type: String
    NoEcho: true
  OperatorEmail:
    Type: String
Resources:
  # !! IMPORTANT !! - CF cannot remove user with an attached MFA device.  Manully deactivate MFA before deleting users.
  # https://docs.aws.amazon.com/cli/latest/reference/iam/deactivate-mfa-device.html
  AWSIAMXavierSchildwachterUser:
    Type: 'AWS::IAM::User'
    Properties:
      UserName: x.schildwachter@sagebase.org
      Groups:
        - !Ref AWSIAMPowerUsersGroup
      LoginProfile:
        Password: !Ref InitNewUserPassword
        PasswordResetRequired: true
  AWSIAMKhaiDoUser:
    Type: 'AWS::IAM::User'
    Properties:
      UserName: khai.do@sagebase.org
      Groups:
        - !Ref AWSIAMPowerUsersGroup
      LoginProfile:
        Password: !Ref InitNewUserPassword
        PasswordResetRequired: true
  AWSIAMAlxDarkUser:
    Type: 'AWS::IAM::User'
    Properties:
      UserName: alx.dark@sagebase.org
      Groups:
        - !Ref AWSIAMPowerUsersGroup
      LoginProfile:
        Password: !Ref InitNewUserPassword
        PasswordResetRequired: true
  AWSIAMPowerUsersGroup:
    Type: 'AWS::IAM::Group'
    Properties:
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/PowerUserAccess
        - arn:aws:iam::aws:policy/IAMReadOnlyAccess
        - !ImportValue bootstrap-EnforceMfaPolicy
  # resources for auditors
  JacobianAccessPolicy:
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Deny
            Action:
            - s3:GetObject
            - s3:GetObjectVersion
            - codecommit:GetCommit
            - codecommit:GitPull
            - dynamodb:BatchGetItem
            - dynamodb:GetItem
            - dynamodb:GetRecords
            - sqs:ReceiveMessage
            - sdb:Select
            Resource: "*"
  AWSIAMJacobianUser:
    Type: 'AWS::IAM::User'
    Properties:
      Groups:
        - !Ref AWSIAMAuditorsGroup
      LoginProfile:
        Password: !Ref JacobianUserPassword
  AWSIAMAuditorsGroup:
    Type: 'AWS::IAM::Group'
    Properties:
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/ReadOnlyAccess
        - !Ref JacobianAccessPolicy
        - !ImportValue bootstrap-EnforceMfaPolicy
  # resources for logging services
  AWSIAMSumoLogicUser:
    Type: 'AWS::IAM::User'
    Properties:
      Groups:
        - !Ref AWSIAMLoggingServiceGroup
  AWSIAMSumoLogicUserAccessKey:
    Type: 'AWS::IAM::AccessKey'
    Properties:
      UserName: !Ref AWSIAMSumoLogicUser
  IAMLoggingServiceManagedPolicy:
    Type: "AWS::IAM::ManagedPolicy"
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - 's3:GetObject'
              - 's3:GetObjectVersion'
              - 's3:ListBucketVersions'
              - 's3:ListBucket'
            Effect: Allow
            Resource:
              - !Join
                - ''
                - - 'arn:aws:s3:::elasticbeanstalk-'
                  - !Ref AWS::Region
                  - '-'
                  - !Ref AWS::AccountId
                  - '/*'
              - !Join
                - ''
                - - 'arn:aws:s3:::elasticbeanstalk-'
                  - !Ref AWS::Region
                  - '-'
                  - !Ref AWS::AccountId
              - !Join
                - ''
                - - 'arn:aws:s3:::'
                  - !Ref AWSS3CloudtrailBucket
                  - '/AWSLogs/'
                  - !Ref AWS::AccountId
                  - '/*'
              - !Join
                - ''
                - - 'arn:aws:s3:::'
                  - !Ref AWSS3CloudtrailBucket
                  - '/AWSLogs/'
                  - !Ref AWS::AccountId
  AWSIAMLoggingServiceGroup:
    Type: 'AWS::IAM::Group'
    Properties:
      ManagedPolicyArns:
        - !Ref IAMLoggingServiceManagedPolicy
  # resources for app monitoring services
  AWSIAMNewRelicBudgetPolicy:
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyName: "NewRelicBudgetPolicy"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Action: "budgets:ViewBudget"
            Resource: "*"
      Roles:
        -
          Ref: AWSIAMNewRelicInfrastructureServiceRole
  AWSIAMNewRelicInfrastructureServiceRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS:
                - !Join
                  - ''
                  - - 'arn:aws:iam::'
                    - !Ref NewRelicAccountId
                    - ':root'
            Action:
              - 'sts:AssumeRole'
            Condition:
              StringEquals:
                sts:ExternalId: !Ref NewRelicExternalId
      Path: /
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/ReadOnlyAccess'
  # resources for cloudtrail
  AWSS3CloudtrailBucket:
    DeletionPolicy: Retain
    Type: "AWS::S3::Bucket"
    Properties: {}
  AWSIAMS3CloudtrailBucketPolicy:
    Type: "AWS::S3::BucketPolicy"
    Properties:
      Bucket: !Ref AWSS3CloudtrailBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Sid: "AWSCloudTrailAclCheck"
            Effect: "Allow"
            Principal:
              Service: "cloudtrail.amazonaws.com"
            Action: "s3:GetBucketAcl"
            Resource:
              !Sub |-
                arn:aws:s3:::${AWSS3CloudtrailBucket}
          -
            Sid: "AWSCloudTrailWrite"
            Effect: "Allow"
            Principal:
              Service: "cloudtrail.amazonaws.com"
            Action: "s3:PutObject"
            Resource:
              !Sub |-
                arn:aws:s3:::${AWSS3CloudtrailBucket}/AWSLogs/${AWS::AccountId}/*
            Condition:
              StringEquals:
                s3:x-amz-acl: "bucket-owner-full-control"
  AWSSNSCloudtrailTopic:
    Type: "AWS::SNS::Topic"
    Properties:
      Subscription:
        -
          Endpoint: !Ref OperatorEmail
          Protocol: email
  AWSSNSCloudtrailTopicPolicy:
    Type: "AWS::SNS::TopicPolicy"
    Properties:
      Topics:
        - !Ref AWSSNSCloudtrailTopic
      PolicyDocument:
        Version: "2008-10-17"
        Statement:
          -
            Sid: "CloudtrailTopicPolicy"
            Effect: "Allow"
            Principal:
              Service: "cloudtrail.amazonaws.com"
            Resource: "*"
            Action: "SNS:Publish"
  AWSCloudtrailTrail:
    DependsOn:
      - AWSIAMS3CloudtrailBucketPolicy
      - AWSSNSCloudtrailTopicPolicy
    Type: "AWS::CloudTrail::Trail"
    Properties:
      S3BucketName: !Ref AWSS3CloudtrailBucket
      SnsTopicName: !GetAtt AWSSNSCloudtrailTopic.TopicName
      IsLogging: true
  # dynamodb monitoring resources
  AWSSNSDynamoTopic:
    Type: "AWS::SNS::Topic"
    Properties:
      Subscription:
        -
          Endpoint: !Ref OperatorEmail
          Protocol: email
  AWSCWDynmoGetRecordsErrorAlarm:
    Type: "AWS::CloudWatch::Alarm"
    Properties:
      ActionsEnabled: true
      AlarmActions:
        - !Ref AWSSNSDynamoTopic
      ComparisonOperator: GreaterThanOrEqualToThreshold
      EvaluationPeriods: 1
      MetricName: SystemErrors
      Namespace: AWS/DynamoDB
      Dimensions:
        -
          "Name": "Operation"
          "Value": "GetRecords"
      Period: 900
      Statistic: Maximum
      Threshold: 1
  AWSCWDynamoDashboard:
    Type: 'AWS::CloudWatch::Dashboard'
    Properties:
      DashboardBody: !Join
        - ''
        - - >-
            {"widgets": [
            {"type":"metric", "x":0, "y":0, "width":12, "height":6, "properties":
            {"metrics":[
            [ "AWS/DynamoDB", "SystemErrors", "Operation", "GetRecords", {"stat": "Sum"}]],
            "view": "timeSeries", "stacked": true, "period":300, "stat":"Sum",
            "region":"us-east-1", "title":"DynamoErrors"}}]}
Outputs:
  AWSIAMSumoLogicUser:
    Value: !Ref AWSIAMSumoLogicUser
    Export:
      Name: !Sub '${AWS::StackName}-SumoLogicUser'
  AWSIAMSumoLogicUserAccessKey:
    Value: !Ref AWSIAMSumoLogicUserAccessKey
    Export:
      Name: !Sub '${AWS::StackName}-SumoLogicUserAccessKey'
  AWSIAMSumoLogicUserSecretAccessKey:
    Value: !GetAtt AWSIAMSumoLogicUserAccessKey.SecretAccessKey
    Export:
      Name: !Sub '${AWS::StackName}-SumoLogicSecretAccessKey'
  AWSS3CloudtrailBucket:
    Value: !Ref AWSS3CloudtrailBucket
    Export:
      Name: !Sub '${AWS::StackName}-CloudtrailBucket'
